run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Suggest code simplifications
    - govet         # Examine Go source code and reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis checks
    - unused        # Check for unused constants, variables, functions and types
    - typecheck     # Type-check Go code
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted
    - misspell      # Find commonly misspelled English words
    - gosec         # Inspect source code for security problems
    - goconst       # Find repeated strings that could be replaced by a constant
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
